name: Flutter CI

on:
  push:
    branches:
      - main
      - develop
      - feature/simpele-ci
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      # FVMを使用してFlutterを実行 
      - name: Setup Flutter with FVM
        run: |
          fvm install 3.32.8
          fvm use 3.32.8 --force
      
      - name: Get dependencies
        run: fvm flutter pub get
      
      - name: Generate code
        run: fvm flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Analyze
        run: fvm flutter analyze
      
      - name: Run tests
        run: fvm flutter test