name: Flutter CI

on:
  push:
    branches:
      - main
      - develop
      - feature/simpele-ci
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Analyze
        run: flutter analyze

      - name: Build Android (Debug APK)
        run: flutter build apk --debug

      - name: Build iOS (No CodeSign)
        run: flutter build ios --no-codesign